# Generated by Django 4.2.1 on 2023-06-15 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_delete_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
