# Generated by Django 4.2.1 on 2023-06-15 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_listing_description_remove_listing_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='listing',
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
