# Generated by Django 4.2.1 on 2023-06-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(max_length=256, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.URLField(max_length=1024, verbose_name='IMG'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=32, verbose_name='Title'),
        ),
    ]
