# Generated by Django 4.2.1 on 2023-06-20 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_listing_description_alter_listing_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bid',
        ),
    ]
